/**
 * @generated
 * @file ButtonSecondary (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://rc-sestek.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import HtmlEmbed from "../webflow_modules/Embed/components/HtmlEmbed";
import Link from "../webflow_modules/Basic/components/Link";

/**
 * Props for {@link ButtonSecondary}
 */
export type ButtonSecondaryProps = {
  cta?: React.ReactNode;
  link2?: {
    href: string;
    preload?: "prerender" | "prefetch" | "none";
    target?: "_self" | "_blank";
  };
  variant?:
    | "Primary"
    | "Secondary"
    | "Light"
    | "Muted"
    | "Transparent"
    | "transparent white";
};

/**
 * ButtonSecondary
 *
 * @see {@link https://rc-sestek.design.webflow.com | Source site in Webflow}
 */
export function ButtonSecondary({
  cta = "Learn more",

  link2 = {
    href: "#",
  },

  variant = "Primary",
}: ButtonSecondaryProps) {
  const _styleVariantMap = {
    Primary: "",
    Secondary: "w-variant-25be9b62-fe23-dbd2-a202-eecb9a82c64a",
    Light: "w-variant-8df013f9-3ce7-e4b2-224d-0e0d11b482b7",
    Muted: "w-variant-b36a41e2-3544-4e17-6121-991ce7ccc7b8",
    Transparent: "w-variant-4f568a80-ba79-01ed-14af-3ae212debfe8",
    "transparent white": "w-variant-34a2759e-1929-2b26-a6bb-88c6e2438b8d",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block tag={"div"}>
        <Link
          block={"inline"}
          button={false}
          className={`flex items-center text-base gap-2 px-2 py-1 rounded-md button-secondary ${_activeStyleVariant}`}
          options={link2}
        >
          <Block className={`text-sm ${_activeStyleVariant}`} tag={"div"}>
            {cta}
          </Block>
          <HtmlEmbed
            className={`icon-1x1-sm ${_activeStyleVariant}`}
            content={
              '<svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" viewBox="0 0 24 24"><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M4.5 12h15m0 0l-5.625-6m5.625 6l-5.625 6"/></svg>'
            }
          />
        </Link>
      </Block>
    </div>
  );
}
