/**
 * @generated
 * @file ButtunGlow (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://rc-sestek.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import Link from "../webflow_modules/Basic/components/Link";

/**
 * Props for {@link ButtunGlow}
 */
export type ButtunGlowProps = {
  link?: {
    href: string;
    preload?: "prerender" | "prefetch" | "none";
    target?: "_self" | "_blank";
  };
  text?: React.ReactNode;
  variant?: "White Text" | "Dark BG" | "White BG" | "Brand Secondary";
};

/**
 * ButtunGlow
 *
 * @see {@link https://rc-sestek.design.webflow.com | Source site in Webflow}
 */
export function ButtunGlow({
  link = {
    href: "#",
  },

  text = "This is some text inside of a div block.",
  variant = "White Text",
}: ButtunGlowProps) {
  const _styleVariantMap = {
    "White Text": "",
    "Dark BG": "w-variant-a2e25307-bbf8-7d45-24c1-40f9e528cd1a",
    "White BG": "w-variant-b24bcec1-f596-e08c-98b8-ae883ae05f3f",
    "Brand Secondary": "w-variant-e24e9192-831f-cdef-c586-c271aea3111c",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Link
        block={"inline"}
        button={false}
        className={`btn-stagger px-4 py-2 rounded-full btn-secondary ${_activeStyleVariant}`}
        options={link}
        stagger-up-animate={""}
      >
        <Block
          className={`text-wrap relative flex gap-custom overflow-hidden ${_activeStyleVariant}`}
          tag={"div"}
        >
          <Block
            className={`btn-text ${_activeStyleVariant}`}
            stagger-btn-text={""}
            tag={"div"}
          >
            {text}
          </Block>
        </Block>
      </Link>
    </div>
  );
}
