/**
 * @generated
 * @file SectionFooterCta (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://rc-sestek.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import Heading from "../webflow_modules/Basic/components/Heading";
import HFlex from "../webflow_modules/Layout/components/HFlex";
import HtmlEmbed from "../webflow_modules/Embed/components/HtmlEmbed";
import Image from "../webflow_modules/Basic/components/Image";
import Section from "../webflow_modules/Layout/components/Section";
import VFlex from "../webflow_modules/Layout/components/VFlex";
import { ButtonSecondary } from "../buttons/ButtonSecondary";

/**
 * Props for {@link SectionFooterCta}
 */
export type SectionFooterCtaProps = {
  buttonSecondaryLink?: {
    href: string;
    preload?: "prerender" | "prefetch" | "none";
    target?: "_self" | "_blank";
  };
  buttonSecondaryText?: React.ReactNode;
  buttonSecondaryVariant?:
    | "Primary"
    | "Secondary"
    | "Light"
    | "Muted"
    | "Transparent"
    | "transparent white";
  image?: string;
  text1?: React.ReactNode;
  text2?: React.ReactNode;
  text3?: React.ReactNode;
  text4?: React.ReactNode;
  text5?: React.ReactNode;
  text6?: React.ReactNode;
  title?: React.ReactNode;
};

/**
 * SectionFooterCta
 *
 * @see {@link https://rc-sestek.design.webflow.com | Source site in Webflow}
 */
export function SectionFooterCta({
  buttonSecondaryLink = {
    href: "#",
  },

  buttonSecondaryText = "Contact us",
  buttonSecondaryVariant = "Primary",
  image = "https://cdn.prod.website-files.com/6a15f6e39b139e2c81103be6/6a40ffb2a31cc01514b73be0_696519293eb77f91651528fb_canvas-preview_jasper%20(1).webp",
  text1 = "We’re invested in your success",
  text2 = "From implementation support to in-the-moment troubleshooting, we’re here to help you build, scale, and optimize your sites.",
  text3 = "Onboarding and training",
  text4 = "Onboarding and training",
  text5 = "Onboarding and training",
  text6 = "Onboarding and training",
  title = "Ready to try Sestek?",
}: SectionFooterCtaProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Section
        className={
          "section__footer-cta overflow-hidden relative view-px sc-py-4 tablet"
        }
        grid={{
          type: "section",
        }}
        tag={"section"}
      >
        <Block
          className={
            "container-2xl relative z-20 flex justify-between tablet gap-2xl"
          }
          tag={"div"}
        >
          <VFlex className={"_w-1-3 gap-8 cta-footer items-start"} tag={"div"}>
            <VFlex className={"gap-2"} tag={"div"}>
              <Heading className={"display-3"} tag={"h2"}>
                {title}
              </Heading>
              <Block tag={"div"}>{text1}</Block>
              <Block className={"text-sm"} tag={"div"}>
                {text2}
              </Block>
            </VFlex>
            <VFlex className={"gap-2"} tag={"div"}>
              <HFlex className={"gap-1 items-center"} tag={"div"}>
                <HtmlEmbed
                  className={"icon-1x1-sm text-primary-500"}
                  content={
                    '<svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-circle-check-icon lucide-circle-check"><circle cx="12" cy="12" r="10"/><path d="m9 12 2 2 4-4"/></svg>'
                  }
                />
                <Block className={"text-sm"} tag={"div"}>
                  {text3}
                </Block>
              </HFlex>
              <HFlex className={"gap-1 items-center"} tag={"div"}>
                <HtmlEmbed
                  className={"icon-1x1-sm text-primary-500"}
                  content={
                    '<svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-circle-check-icon lucide-circle-check"><circle cx="12" cy="12" r="10"/><path d="m9 12 2 2 4-4"/></svg>'
                  }
                />
                <Block className={"text-sm"} tag={"div"}>
                  {text4}
                </Block>
              </HFlex>
              <HFlex className={"gap-1 items-center"} tag={"div"}>
                <HtmlEmbed
                  className={"icon-1x1-sm text-primary-500"}
                  content={
                    '<svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-circle-check-icon lucide-circle-check"><circle cx="12" cy="12" r="10"/><path d="m9 12 2 2 4-4"/></svg>'
                  }
                />
                <Block className={"text-sm"} tag={"div"}>
                  {text5}
                </Block>
              </HFlex>
              <HFlex className={"gap-1 items-center"} tag={"div"}>
                <HtmlEmbed
                  className={"icon-1x1-sm text-primary-500"}
                  content={
                    '<svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-circle-check-icon lucide-circle-check"><circle cx="12" cy="12" r="10"/><path d="m9 12 2 2 4-4"/></svg>'
                  }
                />
                <Block className={"text-sm"} tag={"div"}>
                  {text6}
                </Block>
              </HFlex>
            </VFlex>
            <ButtonSecondary variant={buttonSecondaryVariant} />
          </VFlex>
        </Block>
        <Block
          className={"footer__image-wrap z-20 pointer-events-none"}
          tag={"div"}
        >
          <Image
            alt={""}
            className={"cta__image h-full fit-cover"}
            height={"auto"}
            loading={"lazy"}
            src={image}
            width={"auto"}
          />
        </Block>
        <Block
          className={"absolute cover z-10"}
          data-background-image={""}
          data-bg-color={""}
          data-color-one={"#F472B6"}
          data-color-three={"#F472B6"}
          data-color-two={"#ffffff"}
          data-columns={"5"}
          data-distortion={"0.25"}
          data-fluted-glass={"true"}
          data-gloss={"0.3"}
          data-hover={"true"}
          data-hover-intensity={"2.0"}
          data-noise={"0.40"}
          data-sensitivity-one={"0.15"}
          data-sensitivity-three={"0.15"}
          data-sensitivity-two={"0.15"}
          data-shape-type-one={"0"}
          data-shape-type-three={"0"}
          data-shape-type-two={"3"}
          data-shininess={"800"}
          data-size-one={"0.85"}
          data-size-three={"1.3"}
          data-size-two={"1"}
          data-use-blob-one={"false"}
          data-use-blob-two={"false"}
          data-use-three-color={"true"}
          data-width-variation={"1.8"}
          tag={"div"}
        />
        <Block
          className={"footer__cta-overlay z-20 pointer-events-none"}
          tag={"div"}
        />
      </Section>
    </div>
  );
}
