/**
 * @generated
 * @file FooterCta (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://rc-sestek.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";
import Heading from "./webflow_modules/Basic/components/Heading";
import HFlex from "./webflow_modules/Layout/components/HFlex";
import Image from "./webflow_modules/Basic/components/Image";
import Section from "./webflow_modules/Layout/components/Section";
import VFlex from "./webflow_modules/Layout/components/VFlex";
import { ButtonSecondary } from "./buttons/ButtonSecondary";
import { ButtunGlow } from "./buttons/ButtunGlow";

/**
 * Props for {@link FooterCta}
 */
export type FooterCtaProps = {
  buttonSecondaryLink?: {
    href: string;
    preload?: "prerender" | "prefetch" | "none";
    target?: "_self" | "_blank";
  };
  buttonSecondaryText?: React.ReactNode;
  buttonSecondaryVariant?:
    | "Primary"
    | "Secondary"
    | "Light"
    | "Muted"
    | "Transparent"
    | "transparent white";
  buttunGlowLink?: {
    href: string;
    preload?: "prerender" | "prefetch" | "none";
    target?: "_self" | "_blank";
  };
  buttunGlowText?: React.ReactNode;
  buttunGlowVariant?: "White Text" | "Dark BG" | "White BG" | "Brand Secondary";
  image1?: string;
  image2?: string;
  text?: React.ReactNode;
  title?: React.ReactNode;
};

/**
 * FooterCta
 *
 * @see {@link https://rc-sestek.design.webflow.com | Source site in Webflow}
 */
export function FooterCta({
  buttonSecondaryLink = {
    href: "#",
  },

  buttonSecondaryText = "Contact us",
  buttonSecondaryVariant = "Transparent",

  buttunGlowLink = {
    href: "#",
  },

  buttunGlowText = "Demos",
  buttunGlowVariant = "White BG",
  image1 = "https://cdn.prod.website-files.com/6a15f6e39b139e2c81103be6/6a40182ce9381decc0492231_ChatGPT%20Image%2027%20Haz%202026%2021_31_59.avif",
  image2 = "https://cdn.prod.website-files.com/6a15f6e39b139e2c81103be6/6a19f72cb04d2bd2867edfd9_image.webp",
  text = "Join 1M+ users today and start making AI videos with 240+ avatars in 160+ languages.",
  title = "Ready to try Sestek?",
}: FooterCtaProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Section
        className={
          "section__footer-cta view-px sc-py-4 relative overflow-hidden"
        }
        grid={{
          type: "section",
        }}
        tag={"section"}
      >
        <Block className={"footer__cta-overlay z-10"} tag={"div"} />
        <Image
          alt={""}
          className={"absolute cover opacity-50 z-5 h-full _w-full"}
          height={"auto"}
          loading={"lazy"}
          src={image1}
          width={"auto"}
        />
        <Block
          className={
            "container-2xl relative z-20 flex justify-between tablet gap-2xl"
          }
          tag={"div"}
        >
          <VFlex className={"_w-1-3 gap-8 cta-footer"} tag={"div"}>
            <Heading className={"display-3"} tag={"h1"}>
              {title}
            </Heading>
            <Block className={"text-lg"} tag={"div"}>
              {text}
            </Block>
            <HFlex className={"flex-wrap gap-8"} tag={"div"}>
              <ButtunGlow
                link={buttunGlowLink}
                text={buttunGlowText}
                variant={buttunGlowVariant}
              />
              <ButtonSecondary variant={buttonSecondaryVariant} />
            </HFlex>
          </VFlex>
          <Block className={"_w-1-2 relative cta-footer"} tag={"div"}>
            <Image
              alt={""}
              className={"footer__cta-image rounded-lg fit-cover"}
              height={"auto"}
              loading={"lazy"}
              src={image2}
              width={"auto"}
            />
          </Block>
        </Block>
      </Section>
    </div>
  );
}
