/**
 * @generated
 * @file Navbar (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://rc-sestek.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";
import DOM from "./webflow_modules/Builtin/components/DOM";
import HtmlEmbed from "./webflow_modules/Embed/components/HtmlEmbed";
import Image from "./webflow_modules/Basic/components/Image";
import Link from "./webflow_modules/Basic/components/Link";
import List from "./webflow_modules/Basic/components/List";
import ListItem from "./webflow_modules/Basic/components/ListItem";
import NavbarWrapper from "./webflow_modules/Navbar/components/NavbarWrapper";
import Span from "./webflow_modules/Basic/components/Span";

/**
 * Props for {@link Navbar}
 */
export type NavbarProps = {
  variant?: "Base" | "Light";
};

/**
 * Navbar
 *
 * @see {@link https://rc-sestek.design.webflow.com | Source site in Webflow}
 */
export function Navbar({ variant = "Base" }: NavbarProps) {
  const _styleVariantMap = {
    Base: "",
    Light: "w-variant-1c33ec98-05cb-a0ed-2273-b6a330068496",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <NavbarWrapper
        className={`nav view-px ${_activeStyleVariant}`}
        config={{
          easing: "ease",
          easing2: "ease",
          duration: 400,
          docHeight: false,
          noScroll: false,
          animation: "default",
          collapse: "medium",
        }}
        data-nav={""}
        data-nav-autohide={""}
        tag={"div"}
      >
        <Block className={`nav__backdrop ${_activeStyleVariant}`} tag={"div"} />
        <Block
          className={`nav__bar ${_activeStyleVariant}`}
          data-nav-bar={""}
          tag={"div"}
        >
          <Block className={`nav__inner ${_activeStyleVariant}`} tag={"div"}>
            <Link
              block={"inline"}
              button={false}
              className={`nav__logo ${_activeStyleVariant}`}
              options={{
                href: "#",
              }}
            >
              <HtmlEmbed
                className={`nav__text ${_activeStyleVariant}`}
                content={
                  '<svg xmlns="http://www.w3.org/2000/svg" width="100%" viewBox="0 0 1038.1 196" role="img" aria-label="Sestek logo" fill="currentColor" style="">\n  <path d="M75.641,121.2c49.385,0,72.342-24.67,72.342-53.363C147.983-1.079,34.8,27.613,34.8-18.241c0-16.358,13.614-29.765,45.381-29.765a96.184,96.184,0,0,1,51.253,15.285l8.809-21.453C124.759-64.9,102.069-70.8,80.179-70.8,31.061-70.8,8.638-46.13,8.638-17.169c0,69.721,113.185,40.76,113.185,86.615,0,16.358-13.881,28.961-46.181,28.961-24.025,0-47.783-9.117-61.664-21.721L4.1,97.6C19.049,111.546,47.078,121.2,75.641,121.2Zm138.01-25.475v-60.6h93.7V12.329h-93.7V-45.325H318.828v-23.33H186.957v187.71H322.565V95.725ZM420.267,121.2c49.385,0,72.342-24.67,72.342-53.363,0-68.916-113.185-40.223-113.185-86.078,0-16.358,13.614-29.765,45.381-29.765a96.184,96.184,0,0,1,51.253,15.285l8.809-21.453C469.385-64.9,446.694-70.8,424.8-70.8c-49.118,0-71.541,24.67-71.541,53.631,0,69.721,113.185,40.76,113.185,86.615,0,16.358-13.881,28.961-46.181,28.961-24.025,0-47.783-9.117-61.664-21.721L348.726,97.6C363.675,111.546,391.7,121.2,420.267,121.2Zm145.752-2.145h26.428V-45.325h64.067v-23.33H501.952v23.33h64.067ZM712.3,95.725v-60.6H806V12.329H712.3V-45.325H817.481v-23.33H685.61v187.71H821.218V95.725Zm284.563,23.33H1028.1L943.212,15.815l79.816-84.469H992.6L891.157,36.194V-68.655H864.463v187.71h26.694V70.518l34.169-34.86Z" transform="translate(-4.1 72.8)" \n</svg>'
                }
              />
            </Link>
            <List
              className={`nav__list ${_activeStyleVariant}`}
              tag={"ul"}
              unstyled={false}
            >
              <ListItem className={_activeStyleVariant}>
                <Link
                  button={true}
                  className={`nav__trigger ${_activeStyleVariant}`}
                  data-nav-trigger={"products"}
                  options={{
                    href: "#",
                  }}
                >
                  {"Products"}
                  <DOM
                    className={`nav__chevron nav__chevron ${_activeStyleVariant}`}
                    fill={"none"}
                    height={"12"}
                    tag={"svg"}
                    viewBox={"0 0 12 12"}
                    width={"12"}
                  >
                    <DOM
                      d={"M2 4L6 8L10 4"}
                      stroke={"currentColor"}
                      strokeLinecap={"round"}
                      strokeLinejoin={"round"}
                      strokeWidth={"1.5"}
                      tag={"path"}
                    />
                  </DOM>
                </Link>
              </ListItem>
              <ListItem>
                <Link
                  button={true}
                  className={`nav__trigger ${_activeStyleVariant}`}
                  data-nav-trigger={"solutions"}
                  options={{
                    href: "#",
                  }}
                >
                  {"Solutions"}
                  <DOM
                    className={`nav__chevron nav__chevron ${_activeStyleVariant}`}
                    fill={"none"}
                    height={"12"}
                    tag={"svg"}
                    viewBox={"0 0 12 12"}
                    width={"12"}
                  >
                    <DOM
                      d={"M2 4L6 8L10 4"}
                      stroke={"currentColor"}
                      strokeLinecap={"round"}
                      strokeLinejoin={"round"}
                      strokeWidth={"1.5"}
                      tag={"path"}
                    />
                  </DOM>
                </Link>
              </ListItem>
              <ListItem>
                <Link
                  button={true}
                  className={`nav__trigger ${_activeStyleVariant}`}
                  data-nav-trigger={"company"}
                  options={{
                    href: "#",
                  }}
                >
                  {"Company"}
                  <DOM
                    className={`nav__chevron nav__chevron ${_activeStyleVariant}`}
                    fill={"none"}
                    height={"12"}
                    tag={"svg"}
                    viewBox={"0 0 12 12"}
                    width={"12"}
                  >
                    <DOM
                      d={"M2 4L6 8L10 4"}
                      stroke={"currentColor"}
                      strokeLinecap={"round"}
                      strokeLinejoin={"round"}
                      strokeWidth={"1.5"}
                      tag={"path"}
                    />
                  </DOM>
                </Link>
              </ListItem>
              <ListItem>
                <Link
                  button={false}
                  className={`nav__link ${_activeStyleVariant}`}
                  options={{
                    href: "/pricing",
                  }}
                >
                  {"Pricing"}
                </Link>
              </ListItem>
            </List>
            <Block
              className={`nav__actions ${_activeStyleVariant}`}
              tag={"div"}
            >
              <Link
                button={false}
                className={`nav__link ${_activeStyleVariant}`}
                options={{
                  href: "/login",
                }}
              >
                {"Log in"}
              </Link>
              <Link
                button={false}
                className={`nav__btn ${_activeStyleVariant}`}
                options={{
                  href: "/demo",
                }}
              >
                {"Get a demo"}
              </Link>
            </Block>
            <Link
              aria-label={"Open menu"}
              button={true}
              className={`nav__hamburger ${_activeStyleVariant}`}
              data-nav-hamburger={""}
              options={{
                href: "#",
              }}
            >
              <Span />
              <Span />
              <Span />
            </Link>
          </Block>
        </Block>
        <Block
          className={`nav__dropdown-wrap ${_activeStyleVariant}`}
          tag={"div"}
        >
          <Block
            className={`nav__dropdown ${_activeStyleVariant}`}
            data-nav-dropdown={""}
            tag={"div"}
          >
            <Block
              className={`nav__panel ${_activeStyleVariant}`}
              data-nav-panel={"products"}
              tag={"div"}
            >
              <Block
                className={`nav__panel-layout ${_activeStyleVariant}`}
                tag={"div"}
              >
                <Block
                  className={`nav__panel-body py-4 px-4 ${_activeStyleVariant}`}
                  tag={"div"}
                >
                  <Block
                    className={`nav__panel-rows ${_activeStyleVariant}`}
                    tag={"div"}
                  >
                    <Block
                      className={`nav__panel-row ${_activeStyleVariant}`}
                      tag={"div"}
                    >
                      <Block
                        className={`nav__col ${_activeStyleVariant}`}
                        id={
                          "w-node-_52882d09-e82b-1f15-3173-571cc03d0a17-c03d09ee"
                        }
                        tag={"div"}
                      >
                        <Span
                          className={`nav__col-label ${_activeStyleVariant}`}
                        >
                          {"Platform"}
                        </Span>
                        <Link
                          block={"inline"}
                          button={false}
                          className={`nav__item-icon ${_activeStyleVariant}`}
                          options={{
                            href: "#",
                          }}
                        >
                          <Block
                            className={`nav__item-icon-box ${_activeStyleVariant}`}
                            tag={"div"}
                          />
                          <Block
                            className={`nav__item-icon-text ${_activeStyleVariant}`}
                            tag={"div"}
                          >
                            <Span
                              className={`nav__item-title ${_activeStyleVariant}`}
                            >
                              {"Conversational AI"}
                            </Span>
                            <Span
                              className={`nav__item-desc ${_activeStyleVariant}`}
                            >
                              {"Automate customer interactions"}
                            </Span>
                          </Block>
                        </Link>
                        <Link
                          block={"inline"}
                          button={false}
                          className={`nav__item-icon ${_activeStyleVariant}`}
                          options={{
                            href: "#",
                          }}
                        >
                          <Block
                            className={`nav__item-icon-box ${_activeStyleVariant}`}
                            id={
                              "w-node-_52882d09-e82b-1f15-3173-571cc03d0a22-c03d09ee"
                            }
                            tag={"div"}
                          >
                            <HtmlEmbed
                              className={`icon-1x1-md text-base ${_activeStyleVariant}`}
                              content={
                                '<svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" fill="currentColor" class="bi bi-pause-circle" viewBox="0 0 16 16">\n  <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14m0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16"/>\n  <path d="M5 6.25a1.25 1.25 0 1 1 2.5 0v3.5a1.25 1.25 0 1 1-2.5 0zm3.5 0a1.25 1.25 0 1 1 2.5 0v3.5a1.25 1.25 0 1 1-2.5 0z"/>\n</svg>'
                              }
                              id={
                                "w-node-_52882d09-e82b-1f15-3173-571cc03d0a23-c03d09ee"
                              }
                            />
                          </Block>
                          <Block
                            className={`nav__item-icon-text ${_activeStyleVariant}`}
                            tag={"div"}
                          >
                            <Span
                              className={`nav__item-title ${_activeStyleVariant}`}
                            >
                              {"Voice Bot"}
                            </Span>
                            <Span
                              className={`nav__item-desc ${_activeStyleVariant}`}
                            >
                              {"Natural voice experiences"}
                            </Span>
                          </Block>
                        </Link>
                      </Block>
                      <Block
                        className={`nav__col ${_activeStyleVariant}`}
                        tag={"div"}
                      >
                        <Span
                          className={`nav__col-label ${_activeStyleVariant}`}
                        >
                          {"Analytics"}
                        </Span>
                        <Link
                          block={"inline"}
                          button={false}
                          className={`nav__item-icon ${_activeStyleVariant}`}
                          options={{
                            href: "#",
                          }}
                        >
                          <Block
                            className={`nav__item-icon-box ${_activeStyleVariant}`}
                            tag={"div"}
                          />
                          <Block
                            className={`nav__item-icon-text ${_activeStyleVariant}`}
                            tag={"div"}
                          >
                            <Span
                              className={`nav__item-title ${_activeStyleVariant}`}
                            >
                              {"Interaction Analytics"}
                            </Span>
                            <Span
                              className={`nav__item-desc ${_activeStyleVariant}`}
                            >
                              {"100% conversation coverage"}
                            </Span>
                          </Block>
                        </Link>
                        <Link
                          block={"inline"}
                          button={false}
                          className={`nav__item-icon ${_activeStyleVariant}`}
                          options={{
                            href: "#",
                          }}
                        >
                          <Block
                            className={`nav__item-icon-box ${_activeStyleVariant}`}
                            tag={"div"}
                          />
                          <Block
                            className={`nav__item-icon-text ${_activeStyleVariant}`}
                            tag={"div"}
                          >
                            <Span
                              className={`nav__item-title ${_activeStyleVariant}`}
                            >
                              {"Quality Management"}
                            </Span>
                            <Span
                              className={`nav__item-desc ${_activeStyleVariant}`}
                            >
                              {"AI-powered QA scoring"}
                            </Span>
                          </Block>
                        </Link>
                      </Block>
                      <Block
                        className={`nav__col ${_activeStyleVariant}`}
                        tag={"div"}
                      >
                        <Span
                          className={`nav__col-label ${_activeStyleVariant}`}
                        >
                          {"Agent Tools"}
                        </Span>
                        <Link
                          block={"inline"}
                          button={false}
                          className={`nav__item-icon ${_activeStyleVariant}`}
                          options={{
                            href: "#",
                          }}
                        >
                          <Block
                            className={`nav__item-icon-box ${_activeStyleVariant}`}
                            tag={"div"}
                          />
                          <Block
                            className={`nav__item-icon-text ${_activeStyleVariant}`}
                            tag={"div"}
                          >
                            <Span
                              className={`nav__item-title ${_activeStyleVariant}`}
                            >
                              {"Agent Copilot"}
                            </Span>
                            <Span
                              className={`nav__item-desc ${_activeStyleVariant}`}
                            >
                              {"Real-time agent assistance"}
                            </Span>
                          </Block>
                        </Link>
                        <Link
                          block={"inline"}
                          button={false}
                          className={`nav__item-icon ${_activeStyleVariant}`}
                          options={{
                            href: "#",
                          }}
                        >
                          <Block
                            className={`nav__item-icon-box ${_activeStyleVariant}`}
                            tag={"div"}
                          />
                          <Block
                            className={`nav__item-icon-text ${_activeStyleVariant}`}
                            tag={"div"}
                          >
                            <Span
                              className={`nav__item-title ${_activeStyleVariant}`}
                            >
                              {"Workforce Management"}
                            </Span>
                            <Span
                              className={`nav__item-desc ${_activeStyleVariant}`}
                            >
                              {"Smart scheduling and forecasting"}
                            </Span>
                          </Block>
                        </Link>
                      </Block>
                    </Block>
                  </Block>
                </Block>
                <Block
                  className={`nav__col nav__col--featured ${_activeStyleVariant}`}
                  tag={"div"}
                >
                  <Link
                    block={"inline"}
                    button={false}
                    className={`nav__featured-card ${_activeStyleVariant}`}
                    options={{
                      href: "#",
                    }}
                  >
                    <Image
                      alt={"Featured"}
                      className={`nav__featured-card-image ${_activeStyleVariant}`}
                      height={"auto"}
                      src={
                        "https://cdn.prod.website-files.com/6a15f6e39b139e2c81103be6/6a18425471435c1aee9da174_logo-final.svg"
                      }
                      width={"auto"}
                    />
                    <Block
                      className={`nav__featured-card-body ${_activeStyleVariant}`}
                      tag={"div"}
                    >
                      <Span
                        className={`nav__item-title ${_activeStyleVariant}`}
                      >
                        {"Featured Article"}
                      </Span>
                      <Span className={`nav__item-desc ${_activeStyleVariant}`}>
                        {"Short description goes here"}
                      </Span>
                    </Block>
                  </Link>
                </Block>
              </Block>
            </Block>
            <Block
              className={`nav__panel ${_activeStyleVariant}`}
              data-nav-panel={"solutions"}
              tag={"div"}
            >
              <Block
                className={`nav__panel-layout ${_activeStyleVariant}`}
                tag={"div"}
              >
                <Block
                  className={`nav__panel-body ${_activeStyleVariant}`}
                  tag={"div"}
                >
                  <Block
                    className={`nav__panel-rows ${_activeStyleVariant}`}
                    tag={"div"}
                  >
                    <Block
                      className={`nav__panel-row ${_activeStyleVariant}`}
                      tag={"div"}
                    >
                      <Block
                        className={`nav__col ${_activeStyleVariant}`}
                        tag={"div"}
                      >
                        <Span
                          className={`nav__col-label ${_activeStyleVariant}`}
                        >
                          {"By Industry"}
                        </Span>
                        <Link
                          button={false}
                          className={`nav__item-plain ${_activeStyleVariant}`}
                          options={{
                            href: "#",
                          }}
                        >
                          {"Banking and Finance"}
                        </Link>
                        <Link
                          button={false}
                          className={`nav__item-plain ${_activeStyleVariant}`}
                          options={{
                            href: "#",
                          }}
                        >
                          {"Retail and E-commerce"}
                        </Link>
                        <Link
                          button={false}
                          className={`nav__item-plain ${_activeStyleVariant}`}
                          options={{
                            href: "#",
                          }}
                        >
                          {"Telecom"}
                        </Link>
                      </Block>
                      <Block
                        className={`nav__col ${_activeStyleVariant}`}
                        tag={"div"}
                      >
                        <Span
                          className={`nav__col-label ${_activeStyleVariant}`}
                        >
                          {"By Use Case"}
                        </Span>
                        <Link
                          button={false}
                          className={`nav__item-plain ${_activeStyleVariant}`}
                          options={{
                            href: "#",
                          }}
                        >
                          {"Customer Service"}
                        </Link>
                        <Link
                          button={false}
                          className={`nav__item-plain ${_activeStyleVariant}`}
                          options={{
                            href: "#",
                          }}
                        >
                          {"Sales and Collections"}
                        </Link>
                        <Link
                          button={false}
                          className={`nav__item-plain ${_activeStyleVariant}`}
                          options={{
                            href: "#",
                          }}
                        >
                          {"HR and IT Support"}
                        </Link>
                      </Block>
                      <Block
                        className={`nav__col ${_activeStyleVariant}`}
                        tag={"div"}
                      >
                        <Span
                          className={`nav__col-label ${_activeStyleVariant}`}
                        >
                          {"Integrations"}
                        </Span>
                        <Link
                          button={false}
                          className={`nav__item-highlight ${_activeStyleVariant}`}
                          options={{
                            href: "#",
                          }}
                        >
                          <Span
                            className={`nav__item-title ${_activeStyleVariant}`}
                          >
                            {"All Integrations"}
                          </Span>
                          <Span
                            className={`nav__item-desc ${_activeStyleVariant}`}
                          >
                            {"Connect your tech stack"}
                          </Span>
                        </Link>
                      </Block>
                    </Block>
                  </Block>
                </Block>
                <Block
                  className={`nav__col nav__col--featured ${_activeStyleVariant}`}
                  tag={"div"}
                >
                  <Link
                    block={"inline"}
                    button={false}
                    className={`nav__featured-card ${_activeStyleVariant}`}
                    options={{
                      href: "#",
                    }}
                  >
                    <Image
                      alt={"Featured"}
                      className={`nav__featured-card-image ${_activeStyleVariant}`}
                      height={"auto"}
                      width={"auto"}
                    />
                    <Block
                      className={`nav__featured-card-body ${_activeStyleVariant}`}
                      tag={"div"}
                    >
                      <Span
                        className={`nav__item-title ${_activeStyleVariant}`}
                      >
                        {"Featured Article"}
                      </Span>
                      <Span className={`nav__item-desc ${_activeStyleVariant}`}>
                        {"Short description goes here"}
                      </Span>
                    </Block>
                  </Link>
                </Block>
              </Block>
            </Block>
            <Block
              className={`nav__panel ${_activeStyleVariant}`}
              data-nav-panel={"company"}
              tag={"div"}
            >
              <Block
                className={`nav__panel-layout ${_activeStyleVariant}`}
                tag={"div"}
              >
                <Block
                  className={`nav__panel-body ${_activeStyleVariant}`}
                  tag={"div"}
                >
                  <Block
                    className={`nav__panel-rows ${_activeStyleVariant}`}
                    tag={"div"}
                  >
                    <Block
                      className={`nav__panel-row ${_activeStyleVariant}`}
                      tag={"div"}
                    >
                      <Block
                        className={`nav__col ${_activeStyleVariant}`}
                        tag={"div"}
                      >
                        <Span
                          className={`nav__col-label ${_activeStyleVariant}`}
                        >
                          {"About"}
                        </Span>
                        <Link
                          button={false}
                          className={`nav__item-plain ${_activeStyleVariant}`}
                          options={{
                            href: "#",
                          }}
                        >
                          {"Our Story"}
                        </Link>
                        <Link
                          button={false}
                          className={`nav__item-plain ${_activeStyleVariant}`}
                          options={{
                            href: "#",
                          }}
                        >
                          {"Leadership"}
                        </Link>
                        <Link
                          button={false}
                          className={`nav__item-plain ${_activeStyleVariant}`}
                          options={{
                            href: "#",
                          }}
                        >
                          {"Careers"}
                        </Link>
                      </Block>
                      <Block
                        className={`nav__col ${_activeStyleVariant}`}
                        tag={"div"}
                      >
                        <Span
                          className={`nav__col-label ${_activeStyleVariant}`}
                        >
                          {"Resources"}
                        </Span>
                        <Link
                          button={false}
                          className={`nav__item-plain ${_activeStyleVariant}`}
                          options={{
                            href: "#",
                          }}
                        >
                          {"Blog"}
                        </Link>
                        <Link
                          button={false}
                          className={`nav__item-plain ${_activeStyleVariant}`}
                          options={{
                            href: "#",
                          }}
                        >
                          {"Case Studies"}
                        </Link>
                        <Link
                          button={false}
                          className={`nav__item-plain ${_activeStyleVariant}`}
                          options={{
                            href: "#",
                          }}
                        >
                          {"Webinars"}
                        </Link>
                      </Block>
                      <Block
                        className={`nav__col ${_activeStyleVariant}`}
                        tag={"div"}
                      >
                        <Span
                          className={`nav__col-label ${_activeStyleVariant}`}
                        >
                          {"Contact"}
                        </Span>
                        <Link
                          button={false}
                          className={`nav__item-highlight ${_activeStyleVariant}`}
                          options={{
                            href: "#",
                          }}
                        >
                          <Span
                            className={`nav__item-title ${_activeStyleVariant}`}
                          >
                            {"Contact Sales"}
                          </Span>
                          <Span
                            className={`nav__item-desc ${_activeStyleVariant}`}
                          >
                            {"Talk to our team"}
                          </Span>
                        </Link>
                      </Block>
                    </Block>
                  </Block>
                </Block>
                <Block
                  className={`nav__col nav__col--featured ${_activeStyleVariant}`}
                  tag={"div"}
                >
                  <Link
                    block={"inline"}
                    button={false}
                    className={`nav__featured-card ${_activeStyleVariant}`}
                    options={{
                      href: "#",
                    }}
                  >
                    <Image
                      alt={"Featured"}
                      className={`nav__featured-card-image ${_activeStyleVariant}`}
                      height={"auto"}
                      width={"auto"}
                    />
                    <Block
                      className={`nav__featured-card-body ${_activeStyleVariant}`}
                      tag={"div"}
                    >
                      <Span
                        className={`nav__item-title ${_activeStyleVariant}`}
                      >
                        {"Featured Article"}
                      </Span>
                      <Span className={`nav__item-desc ${_activeStyleVariant}`}>
                        {"Short description goes here"}
                      </Span>
                    </Block>
                  </Link>
                </Block>
              </Block>
            </Block>
          </Block>
        </Block>
        <Block
          className={`nav__overlay ${_activeStyleVariant}`}
          data-nav-overlay={""}
          tag={"div"}
        />
        <Block
          aria-hidden={"true"}
          className={`nav__mobile ${_activeStyleVariant}`}
          data-nav-mobile={""}
          tag={"div"}
        >
          <Block
            className={`nav__mobile-head ${_activeStyleVariant}`}
            tag={"div"}
          >
            <Block
              className={`nav__mobile-headleft ${_activeStyleVariant}`}
              tag={"div"}
            >
              <Link
                button={false}
                className={`nav__mobile-brand ${_activeStyleVariant}`}
                data-nav-mobile-brand={""}
                options={{
                  href: "/",
                }}
              >
                {"Logo"}
              </Link>
              <Link
                button={true}
                className={`nav__mobile-back ${_activeStyleVariant}`}
                data-nav-mobile-back={""}
                options={{
                  href: "#",
                }}
              >
                <DOM
                  fill={"none"}
                  height={"16"}
                  tag={"svg"}
                  viewBox={"0 0 16 16"}
                  width={"16"}
                >
                  <DOM
                    d={"M10 4L6 8L10 12"}
                    stroke={"currentColor"}
                    strokeLinecap={"round"}
                    strokeLinejoin={"round"}
                    strokeWidth={"1.5"}
                    tag={"path"}
                  />
                </DOM>
                {"Back"}
              </Link>
            </Block>
            <Link
              aria-label={"Close menu"}
              button={true}
              className={`nav__mobile-close ${_activeStyleVariant}`}
              data-nav-mobile-close={""}
              options={{
                href: "#",
              }}
            >
              <DOM
                fill={"none"}
                height={"16"}
                tag={"svg"}
                viewBox={"0 0 16 16"}
                width={"16"}
              >
                <DOM
                  d={"M4 4L12 12M12 4L4 12"}
                  stroke={"currentColor"}
                  strokeLinecap={"round"}
                  strokeLinejoin={"round"}
                  strokeWidth={"1.5"}
                  tag={"path"}
                />
              </DOM>
            </Link>
          </Block>
          <Block
            className={`nav__mobile-body ${_activeStyleVariant}`}
            tag={"div"}
          >
            <Block
              className={`nav__mobile-slider ${_activeStyleVariant}`}
              data-nav-mobile-slider={""}
              tag={"div"}
            >
              <Block
                className={`nav__mobile-screen ${_activeStyleVariant}`}
                tag={"div"}
              >
                <List
                  className={`nav__mobile-list ${_activeStyleVariant}`}
                  tag={"ul"}
                  unstyled={false}
                >
                  <ListItem
                    className={`nav__mobile-item ${_activeStyleVariant}`}
                  >
                    <Link
                      button={true}
                      className={`nav__mobile-trigger-row ${_activeStyleVariant}`}
                      data-nav-mobile-trigger={"products"}
                      options={{
                        href: "#",
                      }}
                    >
                      {"Products"}
                      <DOM
                        className={`nav__mobile-chevron nav__mobile-chevron ${_activeStyleVariant}`}
                        fill={"none"}
                        height={"12"}
                        tag={"svg"}
                        viewBox={"0 0 12 12"}
                        width={"12"}
                      >
                        <DOM
                          d={"M4 2L8 6L4 10"}
                          stroke={"currentColor"}
                          strokeLinecap={"round"}
                          strokeLinejoin={"round"}
                          strokeWidth={"1.5"}
                          tag={"path"}
                        />
                      </DOM>
                    </Link>
                  </ListItem>
                  <ListItem
                    className={`nav__mobile-item ${_activeStyleVariant}`}
                  >
                    <Link
                      button={true}
                      className={`nav__mobile-trigger-row ${_activeStyleVariant}`}
                      data-nav-mobile-trigger={"solutions"}
                      options={{
                        href: "#",
                      }}
                    >
                      {"Solutions"}
                      <DOM
                        className={`nav__mobile-chevron nav__mobile-chevron ${_activeStyleVariant}`}
                        fill={"none"}
                        height={"12"}
                        tag={"svg"}
                        viewBox={"0 0 12 12"}
                        width={"12"}
                      >
                        <DOM
                          d={"M4 2L8 6L4 10"}
                          stroke={"currentColor"}
                          strokeLinecap={"round"}
                          strokeLinejoin={"round"}
                          strokeWidth={"1.5"}
                          tag={"path"}
                        />
                      </DOM>
                    </Link>
                  </ListItem>
                  <ListItem
                    className={`nav__mobile-item ${_activeStyleVariant}`}
                  >
                    <Link
                      button={true}
                      className={`nav__mobile-trigger-row ${_activeStyleVariant}`}
                      data-nav-mobile-trigger={"company"}
                      options={{
                        href: "#",
                      }}
                    >
                      {"Company"}
                      <DOM
                        className={`nav__mobile-chevron nav__mobile-chevron ${_activeStyleVariant}`}
                        fill={"none"}
                        height={"12"}
                        tag={"svg"}
                        viewBox={"0 0 12 12"}
                        width={"12"}
                      >
                        <DOM
                          d={"M4 2L8 6L4 10"}
                          stroke={"currentColor"}
                          strokeLinecap={"round"}
                          strokeLinejoin={"round"}
                          strokeWidth={"1.5"}
                          tag={"path"}
                        />
                      </DOM>
                    </Link>
                  </ListItem>
                  <ListItem
                    className={`nav__mobile-item ${_activeStyleVariant}`}
                  >
                    <Link
                      button={false}
                      className={`nav__mobile-link ${_activeStyleVariant}`}
                      options={{
                        href: "/pricing",
                      }}
                    >
                      {"Pricing"}
                    </Link>
                  </ListItem>
                </List>
              </Block>
              <Block
                className={`nav__mobile-screen nav__mobile-screen--sub ${_activeStyleVariant}`}
                data-nav-mobile-sub={""}
                tag={"div"}
              />
            </Block>
          </Block>
          <Block
            className={`nav__mobile-foot ${_activeStyleVariant}`}
            tag={"div"}
          >
            <Link
              button={false}
              className={`nav__mobile-signin ${_activeStyleVariant}`}
              options={{
                href: "/login",
              }}
            >
              {"Log in"}
            </Link>
            <Link
              button={false}
              className={`nav__mobile-cta ${_activeStyleVariant}`}
              options={{
                href: "/demo",
              }}
            >
              {"Get a demo"}
            </Link>
          </Block>
        </Block>
      </NavbarWrapper>
    </div>
  );
}
